apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/roxas9730/apps.git'
    targetRevision: HEAD
    path: apps/overlays/minikube
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - path: apps/overlays/minikube/prometheus.yaml
    - path: apps/overlays/minikube/grafana.yaml
    - path: apps/overlays/minikube/efk.yaml

