apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/roxas9730/apps.git'  # Reemplaza con tu repositorio
    targetRevision: HEAD
    path: apps/base/logging/elasticsearch
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
