apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/roxas9730/apps.git'  # Cambia por tu repo
    targetRevision: HEAD
    path:  apps/base/monitoring/grafana  # Ruta donde está la configuración de Grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
