apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mi_usuario/mi_repositorio'  # Reemplaza con tu repositorio
    targetRevision: HEAD
    path: apps/base/logging/kibana
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
