apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: logging
data:
  elasticsearch.yml: |
    cluster.name: "minikube-cluster"
    network.host: "0.0.0.0"
    discovery.type: "single-node"

