apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./grafana
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps-repo
  validation: client
