apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: apps-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: git@github.com:roxas9730/apps.git
  ref:
    branch: main
  secretRef:
    name: flux-git-auth
